name: Docker Build & Release

on:
  push:
    branches: [ main ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v1
      - name: SetUp Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login 2 Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: MOOGAA
          password: ${{ secrets.GH_ACTION_TOKEN }}
      - name: Build & Push Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/moogaa/sdx-test0:latest
